name: 'Google Calendar Import'
description: 'Imports Google Calendar into a JSON file'
inputs:
  google-credentials:
    description: string, contents of credentials.json
    required: true
  google-token:
    description: string, contents of token.json
    required: true
  calendar-id:
    description: string, the calendar id to check
    required: true
  json-path:
    description: string, path of the json file in the repo to read/write
    required: true
  repo-token:
    description: string, github env var for repo token
    required: true
branding:
  icon: 'chevron-right'  
  color: 'gray-dark'
runs:
  using: 'node12'
  main: 'index.js'